### ISSUE TITLE
What word would you like to start the generation?

### ISSUE THREAD

**Issue by candeladd** [ParkerBeck/BECK_CSCI2270_FinalProject#1]
Hello, 
So I was running your program and I noticed that once the user chooses a sample file to generate the new story from the are prompted with the question: What word would you like to start the generation?
But how is the user supposed to know any of the words in the sample file with oug going into the directory and opening one of the sample files.  I did this and it seems that the program runs fine from here, but I could not understand how else I could have run the program.  

I think you guys did a great job on this program overall,  it is very interesting how it generates the graph.

**Comment by ParkerBeck** [comment]
Thank you for the input, maybe I can add it so the program will display the three most common words before text generation so the user knows some potential available options. For testing we always just used 'a' and 'the' since it's nearly guaranteed to be in the text file.

**Comment by ParkerBeck** [comment]
I fixed this problem in commit 39705ad3ac9b061ad956875a29e73dea4972d539. Now the user is prompted to enter in a '?' if they want to see the most common words in the file. The number of words printed can be changed based on the input to the printMostCommon(x) function.
