### ISSUE TITLE
Generated files lack an extension

### ISSUE THREAD

**Issue by ccomp** [ParkerBeck/BECK_CSCI2270_FinalProject#2]
Not a very big issue, but the output files lack file extensions. Makes it slightly inconvenient to open them up. I also suggest you put the output files in their own, separate folder instead of cluttering the main directory.

**Comment by ParkerBeck** [comment]
Fixed in commit 0dd227251a1f68523cdaca0a72f66e8c0febbd43. The output files are now saved under the Output sub folder and are .txt files. The std library ofstream isn't able to add files to non-existing folders or create folders, so for files to be generated the Output folder must exist.
